/*
 * action types
 */

// SIGNIN
export const CREATE_USER_WITH_EMAIL_AND_PASSWORD = 'CREATE_USER_WITH_EMAIL_AND_PASSWORD';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

// SIGN OUT
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';

// SIGN UP
export const CREATE_USER_DB = 'CREATE_USER_DB';

// LOGIN
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD = 'SIGN_IN_WITH_EMAIL_AND_PASSWORD';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const USER_SET = 'USER_SET';
export const ERASE_USER = 'ERASE_USER';
export const SET_LOADING = 'SET_LOADING';
export const GET_USER = 'GET_USER';
export const SIGN_IN_WITH_SOCIAL = 'SIGN_IN_WITH_SOCIAL';
export const FETCH_USER = 'FETCH_USER';
export const USER_UPDATE = 'USER_UPDATE';

// LANDING
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';

// Chatroom
export const POST_MESSAGE = 'POST_MESSAGE';
export const POST_MESSAGE_SUCCEEDED = 'POST_MESSAGE_SUCCEEDED';
export const POST_MESSAGE_FAILED = 'POST_MESSAGE_FAILED';
export const SAVE_MESSAGE = 'SAVE_MESSAGE';
export const SCROLL_DOWN = 'SCROLL_DOWN';

export const UPDATE_CHAT_SUCCESS = 'UPDATE_CHAT_SUCCESS';
export const UPDATE_CHAT = 'UPDATE_CHAT';
